name: deploy-container

on: 
  push:
    branches: [ "main" ]
    paths:
      - 'container/**'

defaults: 
  run: 
    working-directory: container

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
      
      - run: npm install
      - run: npm run build

      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'container'
          DEST_DIR: 'container/latest'
          AWS_DEFAULT_REGION: 'us-east-1'
